-- Remplacement complet de la bibliothèque d'exercices (base app cliente)
-- Format = suggestion générique par niveau (à ajuster librement dans l'admin)
delete from exercices;

insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Frontale avec Haltères', 'epaules', 0, 1, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Frontale à la Barre', 'epaules', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Devant à la Barre, Assis', 'epaules', 1, 2, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latérale avec Haltères', 'epaules', 0, 1, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Nuque à la Barre, Assis', 'epaules', 2, 2, 'renfo', '["epaules"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé avec Haltères, Assis', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latéral Poulie', 'epaules', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latéral À La Poulie', 'epaules', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Vertical avec Haltères', 'epaules', 1, 1, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Vertical à la Barre', 'epaules', 1, 2, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Écarté avec Haltères', 'pectoraux', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pec Fly', 'pectoraux', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Couché avec Haltères', 'pectoraux', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Couché à la Barre', 'pectoraux', 1, 2, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Incliné avec Haltères', 'pectoraux', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Incliné à la Barre', 'pectoraux', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pompes', 'pectoraux', 0, 0, 'renfo', '["poignets","epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Décliné avec Haltères', 'pectoraux', 2, 1, 'renfo', '["epaules"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Décliné à la Barre', 'pectoraux', 2, 2, 'renfo', '["epaules"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Face Pull', 'epaules', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Seated Row', 'epaules', 0, 2, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Oiseau Haltère', 'trapezes', 0, 1, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing à la Barre, Buste Penché', 'trapezes', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing à Un Bras avec Haltère, Buste Penché', 'trapezes', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Nuque à la Poulie Haute, Prise Large', 'trapezes', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Poitrine à la Poulie Haute, Prise Large', 'trapezes', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Traction à la Barre Fixe', 'trapezes', 2, 1, 'renfo', '["epaules","poignets"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Soulevé de Terre à la Barre', 'trapezes', 2, 2, 'renfo', '["dos","hanches"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing Poulie Basse', 'dos', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pull Over Poulie', 'dos', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Traction à la Barre Fixe, Prise Inversée', 'dos', 2, 1, 'renfo', '["epaules","poignets"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension du Buste', 'lombaires', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Dip Assist', 'triceps', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension Triceps Poulie', 'triceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à Un Bras avec Haltère, Buste Penché', 'triceps', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à la Barre, Couché', 'triceps', 1, 2, 'renfo', '["poignets","epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Dips sur Banc', 'triceps', 1, 1, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latérale', 'triceps', 0, 1, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Concentré', 'biceps', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Incliné avec Haltères', 'biceps', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl avec Haltères', 'biceps', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl avec Haltères, Prise Marteau', 'biceps', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl à la Barre', 'biceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Poignets à la Barre', 'avant_bras', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Flexion des Poignets à la Barre', 'avant_bras', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Gainage', 'abdominaux', 0, 0, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Crunch', 'abdominaux', 0, 0, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Relevé de Jambes', 'abdominaux', 1, 0, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Relevé du Buste', 'abdominaux', 0, 0, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Crunch avec Rotation', 'obliques', 1, 0, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Flexion Latérale avec Haltère', 'obliques', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Step-up', 'fessiers', 1, 0, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Abduction de la Hanche à la Poulie Basse', 'fessiers', 0, 2, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Abduction de la Hanche, Couché', 'fessiers', 0, 0, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Hip Thrust', 'fessiers', 1, 2, 'renfo', '["hanches"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Fente Banc', 'fessiers', 2, 1, 'renfo', '["genoux"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rdl', 'fessiers', 1, 1, 'renfo', '["dos","hanches"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Abduction', 'fessiers', 0, 2, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension de la Hanche à la Poulie Basse', 'fessiers', 0, 2, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Kick Back', 'fessiers', 0, 2, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pont', 'fessiers', 0, 0, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Fente avec Haltères', 'fessiers', 1, 1, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Fente à la Barre', 'fessiers', 2, 2, 'renfo', '["genoux","dos"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Back Extension', 'quadriceps', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension Fessier', 'quadriceps', 0, 0, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Presse Allongé', 'fessiers', 1, 2, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat Devant à la Barre', 'fessiers', 2, 2, 'renfo', '["genoux","dos"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Pupitre à la Barre, Prise Inversée', 'avant_bras', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Pupitre à la Poulie Basse, Prise Inversée', 'avant_bras', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl à la Barre, Prise Inversée', 'avant_bras', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Marche du Fermier avec Haltères', 'avant_bras', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Marche du Fermier avec Kettlebells', 'avant_bras', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Incliné Alterné avec Rotation avec Haltères', 'biceps', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Incliné avec Rotation avec Haltères', 'biceps', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl avec Rotation avec Haltères', 'biceps', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Pupitre Zottman', 'biceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Pupitre Zottman à Un Bras, Debout', 'biceps', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Zottman', 'biceps', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à la Barre EZ, Couché', 'triceps', 1, 2, 'renfo', '["poignets","epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à la Machine', 'triceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à la Poulie Basse, Buste Penché', 'triceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à la Poulie Basse, Couché', 'triceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à la Poulie Basse, Couché, Prise Marteau', 'triceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à la Poulie Basse, Debout', 'triceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Flexion des Poignets avec Kettlebells', 'avant_bras', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Flexion des Poignets à la Poulie', 'avant_bras', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Planche', 'abdominaux', 0, 0, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Planche Latérale', 'obliques', 0, 0, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Insecte Mort', 'abdominaux', 0, 0, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Insecte Mort avec Ballon', 'abdominaux', 0, 1, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Presse Pallof à la Poulie', 'obliques', 1, 2, 'renfo', '[]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Presse Pallof à la Poulie, à Genoux', 'obliques', 1, 2, 'renfo', '[]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rotation du Buste à la Landmine', 'obliques', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rotation du Buste à la Machine', 'obliques', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rotation Russe', 'obliques', 1, 0, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rotation Russe avec Haltère', 'obliques', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rotation Russe avec Kettlebell', 'obliques', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Couché à la Barre, Prise Large', 'pectoraux', 1, 2, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Couché à la Poulie', 'pectoraux', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Couché à la Smith Machine', 'pectoraux', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Incliné à la Poulie', 'pectoraux', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Incliné à la Smith Machine', 'pectoraux', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pompes Déclinées', 'pectoraux', 1, 1, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pompes Déclinées sur Ballon', 'pectoraux', 2, 1, 'renfo', '["epaules","poignets"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat Gobelet avec Haltère', 'fessiers', 0, 1, 'renfo', '["genoux"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat Gobelet avec Kettlebell', 'fessiers', 0, 1, 'renfo', '["genoux"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat avec Haltères', 'fessiers', 1, 1, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat avec Haltères sur Banc', 'fessiers', 1, 1, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat à la Barre sur Banc', 'fessiers', 2, 2, 'renfo', '["genoux","dos"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat à la Smith Machine', 'fessiers', 1, 2, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Relevé de Bassin avec Haltères', 'fessiers', 1, 1, 'renfo', '["hanches"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Relevé de Bassin sur Ballon', 'fessiers', 1, 1, 'renfo', '["hanches"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Relevé de Bassin à la Barre', 'fessiers', 1, 2, 'renfo', '["hanches"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Relevé de Bassin à la Smith Machine', 'fessiers', 1, 2, 'renfo', '["hanches"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Battement de Jambes Ventral sur Banc', 'fessiers', 1, 1, 'renfo', '["hanches"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension de la Hanche', 'fessiers', 0, 0, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension de la Hanche sur Banc', 'fessiers', 0, 1, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Arraché à Un Bras avec Haltère', 'epaules', 2, 1, 'renfo', '["epaules","dos","poignets"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Arraché à Un Bras avec Kettlebell', 'epaules', 2, 1, 'renfo', '["epaules","dos","poignets"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Arraché à la Barre', 'epaules', 2, 2, 'renfo', '["epaules","dos","poignets"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Swing à Un Bras avec Kettlebell', 'fessiers', 2, 1, 'renfo', '["dos"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Swing avec Haltère', 'fessiers', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Soulevé de Terre à la Barre Hexagonale', 'trapezes', 2, 2, 'renfo', '["dos","hanches"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing Incliné à la Barre, Prise Inversée', 'dos', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing avec Haltères, Buste Penché, Prise Inversée', 'dos', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing à la Barre, Buste Penché, Prise Inversée', 'dos', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing à la Machine, Assis', 'dos', 0, 2, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing à la Poulie Basse, Assis', 'dos', 0, 2, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Split Squat Bulgare avec Haltères', 'fessiers', 2, 1, 'renfo', '["genoux"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Split Squat Bulgare à la Barre', 'fessiers', 2, 2, 'renfo', '["genoux"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Split Squat Bulgare à la Ceinture à la Machine', 'fessiers', 2, 2, 'renfo', '["genoux"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Split Squat Bulgare', 'fessiers', 1, 1, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat Pendule à la Machine', 'fessiers', 1, 2, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat à la Ceinture à la Machine', 'fessiers', 1, 2, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Saut en Étoile', 'full_body', 1, 0, 'cardio', '["genoux","chevilles"]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Jambes à Une Jambe', 'quadriceps', 0, 2, 'renfo', '["genoux"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Jambes à Une Jambe à la Poulie', 'quadriceps', 0, 2, 'renfo', '["genoux"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Presse des Jambes à Une Jambe', 'quadriceps', 1, 2, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Presse des Jambes à Une Jambe, Assis', 'quadriceps', 1, 2, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Presse des Jambes, Assis', 'quadriceps', 0, 2, 'renfo', '["genoux"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Sissy Squat', 'quadriceps', 2, 0, 'renfo', '["genoux"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Sissy Squat avec Disque', 'quadriceps', 2, 1, 'renfo', '["genoux"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat Pistol', 'quadriceps', 2, 0, 'renfo', '["genoux"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat Pistol avec Kettlebell', 'quadriceps', 2, 1, 'renfo', '["genoux"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Chaise', 'quadriceps', 1, 0, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Hack Squat à la Landmine', 'quadriceps', 1, 1, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Hack Squat à la Machine', 'quadriceps', 1, 2, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Swing avec Kettlebell', 'fessiers', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Abduction de la Hanche à la Machine, Assis', 'fessiers', 0, 2, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Abduction de la Hanche à la Machine, Debout', 'fessiers', 0, 2, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Relevé de Bassin', 'fessiers', 0, 0, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Marche du Fermier à la Barre Hexagonale', 'avant_bras', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Flexion des Poignets avec Haltères', 'avant_bras', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latérale avec Haltère, Couché sur le Côté', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latérale à Un Bras à la Poulie Basse', 'epaules', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latérale à la Machine', 'epaules', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latérale à la Poulie Basse', 'epaules', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rotation Interne à la Poulie, Debout', 'epaules', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Frontale Alternée avec Haltères', 'epaules', 0, 1, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Frontale avec Un Haltère', 'epaules', 0, 1, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à la Poulie Basse, Debout, Prise Marteau', 'triceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à la Poulie Haute', 'triceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à la Poulie Haute, Assis', 'triceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à la Poulie Haute, Debout', 'triceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à la Poulie Haute, Prise Marteau', 'triceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à Un Bras à la Poulie Haute, Prise Inversée', 'triceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à la Poulie Haute, Prise Inversée', 'triceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Dips sur Ballon', 'triceps', 1, 1, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Alterné avec Haltères', 'biceps', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Alterné avec Haltères, Prise Marteau', 'biceps', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Alterné à la Machine', 'biceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Araignée avec Haltères', 'biceps', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Araignée avec Haltères, Prise Marteau', 'biceps', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Couché à la Machine', 'pectoraux', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Couché à la Machine, Assis', 'pectoraux', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Couché à la Poulie, Assis', 'pectoraux', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Décliné à la Poulie', 'pectoraux', 2, 2, 'renfo', '["epaules"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Décliné à la Smith Machine', 'pectoraux', 2, 2, 'renfo', '["epaules"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pompes Inclinées', 'pectoraux', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pompes Inclinées sur Ballon', 'pectoraux', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pull-Over avec Haltère', 'pectoraux', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé à Un Bras avec Haltère, Debout', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Vertical avec Kettlebell', 'epaules', 1, 1, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Vertical à Un Bras avec Haltère', 'epaules', 1, 1, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Vertical à la Barre EZ', 'epaules', 1, 2, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Vertical à la Poulie Basse', 'epaules', 1, 2, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage au Visage à la Poulie Basse, Assis', 'epaules', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage au Visage à la Poulie Haute', 'epaules', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Frontale à Un Bras à la Poulie Basse', 'epaules', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Frontale à la Barre, Assis', 'epaules', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Frontale à la Poulie Basse', 'epaules', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Arnold', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Arnold à Un Bras', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Arnold, Debout', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latérale avec Kettlebells', 'epaules', 0, 1, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latérale à la Landmine', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latérale à la Poulie Basse, Buste Penché', 'epaules', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Nuque à la Smith Machine, Assis', 'epaules', 2, 2, 'renfo', '["epaules"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Nuque à la Smith Machine, Debout', 'epaules', 2, 2, 'renfo', '["epaules"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé avec Haltères, Debout', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Poitrine à la Machine', 'dos', 0, 2, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Poitrine à la Poulie Haute', 'dos', 0, 2, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Poitrine à Un Bras à la Poulie Haute, Bras Tendu', 'dos', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Poitrine à la Poulie Haute, Bras Tendus', 'dos', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Poitrine à la Machine, Prise Inversée', 'dos', 0, 2, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Poitrine à la Poulie Haute, Prise Inversée', 'dos', 0, 2, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing à la Landmine', 'dos', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing à la Machine, Assis, Prise Large', 'dos', 0, 2, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing à la Poulie Basse, Assis, Prise Large', 'dos', 0, 2, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing à la Smith Machine, Buste Penché', 'dos', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing Renégat avec Haltères', 'dos', 2, 1, 'renfo', '["dos","poignets"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing Renégat avec Kettlebells', 'dos', 2, 1, 'renfo', '["dos","poignets"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing à Un Bras avec Kettlebell, Buste Penché', 'dos', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing à Un Bras à la Landmine, Buste Penché', 'dos', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Soulevé de Terre avec Haltères', 'trapezes', 1, 1, 'renfo', '["dos","hanches"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Soulevé de Terre à la Smith Machine', 'trapezes', 1, 2, 'renfo', '["dos","hanches"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latérale à la Landmine (Dos)', 'trapezes', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latérale à la Poulie Basse, Buste Penché (Dos)', 'trapezes', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Pupitre Alterné avec Haltères', 'biceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Pupitre Alterné avec Haltères, Prise Marteau', 'biceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Pupitre avec Haltères', 'biceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Pupitre avec Haltères, Prise Marteau', 'biceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Pupitre à Un Bras avec Haltère, Debout', 'biceps', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Pupitre à Un Bras à la Machine', 'biceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl à la Barre EZ, Prise Large', 'biceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl à la Barre, Prise Large', 'biceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl à la Machine', 'biceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl à la Poulie Basse', 'biceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl à la Poulie Basse, Prise Marteau', 'biceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl à la Poulie Haute', 'biceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rameur', 'full_body', 1, 2, 'cardio', '["dos"]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Vélo Stationnaire', 'full_body', 0, 2, 'cardio', '[]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Vélo Elliptique', 'full_body', 0, 2, 'cardio', '[]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Saut Double à la Corde', 'full_body', 2, 1, 'cardio', '["genoux","chevilles"]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Saut à la Corde', 'full_body', 1, 1, 'cardio', '["genoux","chevilles"]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Course sur Tapis Roulant', 'full_body', 0, 2, 'cardio', '["genoux"]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Boxe', 'full_body', 1, 0, 'cardio', '["poignets","epaules"]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Oiseau à la Machine', 'epaules', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Oiseau à la Poulie Haute', 'epaules', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rotation Externe à la Poulie, Debout', 'epaules', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latérale Alternée avec Haltères, Buste Penché', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latérale avec Haltères, Assis', 'epaules', 0, 1, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Latérale avec Haltères, Buste Penché', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Soulevé de Terre Roumain à la Barre', 'lombaires', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Soulevé de Terre avec Haltères, Jambes Tendues', 'lombaires', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Soulevé de Terre à la Barre, Jambes Tendues', 'lombaires', 2, 2, 'renfo', '["dos"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Dips aux Barres Parallèles', 'pectoraux', 2, 2, 'renfo', '["epaules","poignets"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Dips à la Machine', 'pectoraux', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Relevé de Jambes à la Machine', 'abdominaux', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Relevé du Buste Incliné', 'abdominaux', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Roulette avec Haltères', 'abdominaux', 2, 1, 'renfo', '["dos","epaules"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Roulette avec Roue Abdominale', 'abdominaux', 2, 1, 'renfo', '["dos","epaules"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Roulette à la Barre', 'abdominaux', 2, 2, 'renfo', '["dos","epaules"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Roulette à la Barre EZ', 'abdominaux', 2, 2, 'renfo', '["dos","epaules"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Relevé du Buste Incliné avec Rotation', 'obliques', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Relevé du Buste avec Rotation', 'obliques', 1, 0, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Alpiniste', 'abdominaux', 1, 0, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Flexion Latérale à la Poulie Basse', 'obliques', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rotation du Buste à la Barre', 'obliques', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rotation du Buste à la Poulie', 'obliques', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rotation du Buste à la Poulie, Assis', 'obliques', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Presse Pallof à la Poulie, Couché', 'obliques', 1, 2, 'renfo', '[]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Flexion des Jambes, Debout', 'ischio_jambiers', 0, 2, 'renfo', '["genoux"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Mollets avec Haltères, Assis', 'mollets', 0, 1, 'renfo', '["chevilles"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Mollets à Une Jambe avec Haltère, Debout', 'mollets', 1, 1, 'renfo', '["chevilles"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Mollets à Une Jambe à la Smith Machine, Debout', 'mollets', 1, 2, 'renfo', '["chevilles"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Mollets à Une Jambe, Debout', 'mollets', 1, 0, 'renfo', '["chevilles"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Mollets à la Barre, Assis', 'mollets', 0, 2, 'renfo', '["chevilles"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Vélo', 'full_body', 0, 2, 'cardio', '[]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Course', 'full_body', 0, 0, 'cardio', '["genoux"]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing Incliné avec Haltères', 'dos', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing avec Haltères, Buste Penché', 'dos', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing à la Barre T, Buste Penché', 'dos', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing à la Barre T, Couché', 'dos', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing à la Barre, Couché', 'dos', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Poitrine à Un Bras à la Poulie Haute', 'dos', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Poitrine à la Poulie Haute, Prise Serrée', 'dos', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Traction à la Barre Fixe, Prise Serrée', 'dos', 2, 1, 'renfo', '["epaules","poignets"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pull-Over à la Machine', 'dos', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pull-Over à la Poulie Haute, Assis', 'dos', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps Incliné à la Poulie Basse, Prise Marteau', 'triceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps avec Haltères, Couché', 'triceps', 1, 1, 'renfo', '["poignets","epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps avec Un Haltère, Assis', 'triceps', 1, 1, 'renfo', '["poignets","epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps avec Un Haltère, Debout', 'triceps', 1, 1, 'renfo', '["poignets","epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à Un Bras avec Haltère, Assis', 'triceps', 1, 1, 'renfo', '["poignets","epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Araignée à la Barre', 'biceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Araignée à la Barre EZ', 'biceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Concentré avec Kettlebell', 'biceps', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Concentré à la Poulie Basse', 'biceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Couché à la Barre, Prise Large 2', 'pectoraux', 1, 2, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage Poitrine à Un Bras à la Poulie Haute, Bras Tendu 2', 'dos', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Flexion des Jambes, Couché', 'ischio_jambiers', 0, 2, 'renfo', '["genoux"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Mollets à la Machine, Assis', 'mollets', 0, 2, 'renfo', '["chevilles"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Mollets à la Presse', 'mollets', 0, 2, 'renfo', '["chevilles"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Étirement en Fente au Mur, Debout', 'mollets', 0, 0, 'renfo', '[]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat à la Barre, Jambes Écartées', 'quadriceps', 2, 2, 'renfo', '["genoux"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat Sumo à la Ceinture à la Machine', 'quadriceps', 1, 2, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Demi-Burpee', 'full_body', 1, 0, 'cardio', '["genoux","poignets"]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Adducteurs à la Machine', 'adducteurs', 0, 2, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Good Morning à la Barre', 'ischio_jambiers', 2, 2, 'renfo', '["dos"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Ondulations Alternées avec Corde Ondulatoire', 'full_body', 1, 1, 'cardio', '["epaules","poignets"]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Ondulations Simultanées avec Corde Ondulatoire', 'full_body', 1, 1, 'cardio', '["epaules","poignets"]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Ergomètre de Ski', 'full_body', 1, 2, 'cardio', '["epaules"]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Zottman, Assis', 'avant_bras', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Poignets avec Haltères', 'avant_bras', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Poignets à la Poulie', 'avant_bras', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Araignée avec Haltères, Prise Inversée', 'avant_bras', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Pupitre avec Haltères, Prise Inversée', 'avant_bras', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl Pupitre à la Barre EZ, Prise Inversée', 'avant_bras', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Fente avec Kettlebells', 'fessiers', 1, 1, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat avec Un Haltère', 'fessiers', 1, 1, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Jambes', 'quadriceps', 0, 2, 'renfo', '["genoux"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Presse des Jambes', 'quadriceps', 0, 2, 'renfo', '["genoux"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Adducteurs à la Poulie Basse', 'adducteurs', 0, 2, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Hip Abduction', 'adducteurs', 0, 0, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Leg Curl', 'ischio_jambiers', 0, 2, 'renfo', '["genoux"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Flexion des Jambes, Assis', 'ischio_jambiers', 0, 2, 'renfo', '["genoux"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Mollets à la Barre, Debout', 'mollets', 0, 2, 'renfo', '["chevilles"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension du Buste à la Machine', 'lombaires', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension du Buste sur Ballon', 'lombaires', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Superman', 'lombaires', 0, 0, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Soulevé de Terre Sumo à la Barre', 'fessiers', 2, 2, 'renfo', '["dos","hanches"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Soulevé de Terre Roumain avec Kettlebells', 'lombaires', 1, 1, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Haussement d''Épaules avec Haltères', 'trapezes', 0, 1, 'renfo', '[]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Haussement d''Épaules à la Barre', 'trapezes', 0, 2, 'renfo', '[]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Haussement d''Épaules à la Barre Hexagonale', 'trapezes', 0, 2, 'renfo', '[]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Haussement d''Épaules à la Machine', 'trapezes', 0, 2, 'renfo', '[]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pull-Over à la Barre', 'dos', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Arnold, Debout 2', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Devant à la Barre, Debout', 'epaules', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Devant à la Smith Machine, Assis', 'epaules', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Devant à la Smith Machine, Debout', 'epaules', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé à Un Bras à la Landmine, Debout', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé à Un Bras à la Landmine, à Genoux', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à Un Bras à la Poulie Basse sur Banc', 'triceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à Un Bras à la Poulie Basse, Buste Penché', 'triceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à Un Bras à la Poulie Haute, Debout', 'triceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à Un Bras à la Poulie Haute, Prise Marteau', 'triceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps à la Barre EZ, Assis', 'triceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl à Un Bras à la Poulie Basse', 'biceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl à Un Bras à la Poulie Haute', 'biceps', 0, 2, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl à la Barre EZ, Prise Large 2', 'biceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Écarté Décliné avec Haltères', 'pectoraux', 2, 1, 'renfo', '["epaules"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Écarté Incliné avec Haltères', 'pectoraux', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Écarté Incliné à la Poulie', 'pectoraux', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Écarté à la Machine', 'pectoraux', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Écarté à la Poulie', 'pectoraux', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Écarté à la Poulie Basse', 'pectoraux', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Écarté à la Poulie Haute', 'pectoraux', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Incliné à la Machine', 'pectoraux', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Couché avec Haltères, Prise Serrée', 'pectoraux', 1, 1, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Couché à la Barre, Prise Serrée', 'pectoraux', 1, 2, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Incliné avec Haltères, Prise Serrée', 'pectoraux', 1, 1, 'renfo', '["epaules","poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pompes Inclinées, Prise Serrée', 'pectoraux', 1, 1, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pompes, Prise Serrée', 'pectoraux', 1, 0, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Dips aux Barres Parallèles, Prise Serrée', 'pectoraux', 2, 2, 'renfo', '["epaules","poignets"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Couché avec Haltères, Prise Serrée 2', 'pectoraux', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé Couché à la Barre, Prise Serrée 2', 'pectoraux', 1, 2, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps Incliné à la Barre EZ', 'triceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension des Triceps Incliné à la Poulie Basse', 'triceps', 1, 2, 'renfo', '["poignets"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé à la Landmine, Debout', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé à la Landmine, à Genoux', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé à la Machine, Assis', 'epaules', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Frontale Alternée avec Haltères, Prise Marteau', 'epaules', 0, 1, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Frontale à Un Bras avec Haltère, Prise Marteau', 'epaules', 0, 1, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévation Frontale à Un Bras à la Poulie Basse, Prise Marteau', 'epaules', 0, 2, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Crunch à la Poulie Haute, Assis', 'abdominaux', 0, 2, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Crunch à la Poulie Haute, à Genoux', 'abdominaux', 0, 2, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Battement de Jambes', 'abdominaux', 1, 0, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Crunch sur Ballon', 'abdominaux', 0, 1, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Crunch à la Machine', 'abdominaux', 0, 2, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Relevé de Jambes Incliné', 'abdominaux', 1, 2, 'renfo', '["dos"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Relevé de Jambes Suspendu', 'abdominaux', 2, 1, 'renfo', '["dos","epaules"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension de la Hanche à la Machine 2', 'fessiers', 0, 2, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension de la Hanche, Genou Plié', 'fessiers', 0, 0, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pont avec Haltère', 'fessiers', 0, 1, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pont sur Banc', 'fessiers', 0, 1, 'renfo', '["hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pont à la Barre', 'fessiers', 1, 2, 'renfo', '["hanches"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pont à la Barre sur Banc', 'fessiers', 1, 2, 'renfo', '["hanches"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Fente Latérale', 'fessiers', 1, 0, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Fente 2', 'fessiers', 1, 0, 'renfo', '["genoux"]'::jsonb, '3-4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Escaliers Stationnaires', 'full_body', 1, 2, 'cardio', '["genoux"]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Marche', 'full_body', 0, 0, 'cardio', '[]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Marche sur Tapis Roulant', 'full_body', 0, 2, 'cardio', '[]'::jsonb, '15-20 min');
