-- Bibliothèque d'exercices et de recettes, éditable depuis l'espace admin.
-- Étape 1 : exécuter d'abord la création des tables et politiques ci-dessous.
-- Étape 2 : les INSERT en bas de fichier importent la base de départ.

create table if not exists exercices (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  nom text not null,
  zone text not null,
  niveau int not null default 0,
  materiel int not null default 0,
  type text not null default 'renfo',
  contre_indications jsonb default '[]',
  format text
);
alter table exercices enable row level security;
drop policy if exists "authenticated full access" on exercices;
create policy "authenticated full access" on exercices for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create table if not exists recettes (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  nom text not null,
  repas text not null,
  profils jsonb default '[]',
  vegetarien boolean default false,
  vegan boolean default false,
  sans_gluten boolean default false,
  sans_lactose boolean default false,
  contient jsonb default '[]',
  proteines_g int,
  ingredients jsonb default '[]',
  etapes jsonb default '[]'
);
alter table recettes enable row level security;
drop policy if exists "authenticated full access" on recettes;
create policy "authenticated full access" on recettes for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Nouveaux champs sur les fiches clientes : exercices préférés à privilégier,
-- temps prévu pour manger avant le travail, et mots-clés libres à éviter.
alter table clientes add column if not exists exercices_preferes jsonb default '[]';
alter table clientes add column if not exists tampon_repas int default 60;
alter table clientes add column if not exists aliments_evites_libre jsonb default '[]';

-- Import des exercices de départ
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pompes', 'torse', 0, 0, 'renfo', '["poignets","epaules"]'::jsonb, '4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pompes sur les genoux', 'torse', 0, 0, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé couché haltères', 'torse', 1, 1, 'renfo', '["epaules"]'::jsonb, '4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé couché barre', 'torse', 2, 2, 'renfo', '["epaules","poignets"]'::jsonb, '5x6');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Écarté haltères au sol', 'torse', 1, 1, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Dips sur banc', 'torse', 1, 1, 'renfo', '["epaules","poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pompes mains surélevées', 'torse', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pull-over haltère', 'torse', 1, 1, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing haltères buste penché', 'dos', 0, 1, 'renfo', '["dos"]'::jsonb, '4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing élastique', 'dos', 0, 1, 'renfo', '[]'::jsonb, '3x15');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tirage vertical poulie', 'dos', 1, 2, 'renfo', '["epaules"]'::jsonb, '4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Tractions assistées', 'dos', 2, 2, 'renfo', '["epaules","poignets"]'::jsonb, '4x6');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Superman', 'dos', 0, 0, 'renfo', '["dos"]'::jsonb, '3x15');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Good morning léger', 'dos', 1, 1, 'renfo', '["dos"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rowing barre', 'dos', 2, 2, 'renfo', '["dos"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension lombaire au sol', 'dos', 0, 0, 'renfo', '["dos"]'::jsonb, '3x15');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévations latérales haltères', 'epaules', 0, 1, 'renfo', '["epaules"]'::jsonb, '3x15');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé militaire haltères', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Élévations frontales', 'epaules', 0, 1, 'renfo', '["epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Oiseau (deltoïde arrière)', 'epaules', 1, 1, 'renfo', '["epaules"]'::jsonb, '3x15');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pike push-up', 'epaules', 1, 0, 'renfo', '["epaules","poignets"]'::jsonb, '3x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Développé épaules machine', 'epaules', 2, 2, 'renfo', '["epaules"]'::jsonb, '4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl biceps haltères', 'bras', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension triceps haltère', 'bras', 0, 1, 'renfo', '["epaules","poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Dips entre deux chaises', 'bras', 1, 0, 'renfo', '["poignets","epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl marteau', 'bras', 0, 1, 'renfo', '["poignets"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Extension triceps poulie', 'bras', 1, 2, 'renfo', '["poignets"]'::jsonb, '3x15');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Curl barre', 'bras', 1, 2, 'renfo', '["poignets"]'::jsonb, '4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Gainage planche', 'abdos', 0, 0, 'renfo', '["poignets"]'::jsonb, '3x30s');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Gainage latéral', 'abdos', 0, 0, 'renfo', '["epaules"]'::jsonb, '3x20s/côté');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Crunch', 'abdos', 0, 0, 'renfo', '["dos"]'::jsonb, '3x20');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Relevé de jambes suspendu', 'abdos', 2, 2, 'renfo', '["dos","epaules"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Mountain climbers lents', 'abdos', 0, 0, 'renfo', '["poignets"]'::jsonb, '3x20');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Russian twist', 'abdos', 1, 0, 'renfo', '["dos"]'::jsonb, '3x20');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Roulette abdominale', 'abdos', 2, 1, 'renfo', '["dos","epaules"]'::jsonb, '3x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Bicycle crunch', 'abdos', 1, 0, 'renfo', '["dos"]'::jsonb, '3x20');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat poids de corps', 'jambes', 0, 0, 'renfo', '["genoux"]'::jsonb, '4x15');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat gobelet', 'jambes', 0, 1, 'renfo', '["genoux"]'::jsonb, '4x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Fentes alternées', 'jambes', 1, 0, 'renfo', '["genoux"]'::jsonb, '3x12/jambe');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat bulgare', 'jambes', 2, 1, 'renfo', '["genoux","chevilles"]'::jsonb, '3x10/jambe');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Presse à cuisses', 'jambes', 1, 2, 'renfo', '["genoux"]'::jsonb, '4x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Leg extension machine', 'jambes', 1, 2, 'renfo', '["genoux"]'::jsonb, '3x15');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Leg curl machine', 'jambes', 1, 2, 'renfo', '["genoux"]'::jsonb, '3x15');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat barre', 'jambes', 2, 2, 'renfo', '["genoux","dos"]'::jsonb, '5x6');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Mollets debout', 'jambes', 0, 1, 'renfo', '["chevilles"]'::jsonb, '4x15');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Marche fentes avant', 'jambes', 1, 0, 'renfo', '["genoux"]'::jsonb, '3x10/jambe');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Hip thrust poids de corps', 'fessiers', 0, 0, 'renfo', '["hanches"]'::jsonb, '4x15');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Hip thrust chargé', 'fessiers', 1, 1, 'renfo', '["hanches"]'::jsonb, '4x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Pont fessier', 'fessiers', 0, 0, 'renfo', '["hanches"]'::jsonb, '3x15');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Soulevé de terre jambes tendues', 'fessiers', 1, 1, 'renfo', '["dos","hanches"]'::jsonb, '3x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Abduction de hanche élastique', 'fessiers', 0, 1, 'renfo', '["hanches"]'::jsonb, '3x15/côté');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Donkey kick', 'fessiers', 0, 0, 'renfo', '["genoux","hanches"]'::jsonb, '3x15/côté');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Soulevé de terre sumo', 'fessiers', 2, 2, 'renfo', '["dos","hanches"]'::jsonb, '4x8');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Step-up sur banc', 'fessiers', 1, 1, 'renfo', '["genoux"]'::jsonb, '3x10/jambe');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Marche rapide', 'full_body', 0, 0, 'cardio', '[]'::jsonb, '20-30 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Jumping jacks', 'full_body', 0, 0, 'cardio', '["genoux","chevilles"]'::jsonb, '4x30s');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Corde à sauter', 'full_body', 1, 1, 'cardio', '["genoux","chevilles"]'::jsonb, '5x1min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Mountain climbers', 'full_body', 1, 0, 'cardio', '["poignets"]'::jsonb, '4x30s');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Burpees', 'full_body', 2, 0, 'cardio', '["genoux","poignets","epaules"]'::jsonb, '4x10');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Vélo elliptique', 'full_body', 0, 2, 'cardio', '[]'::jsonb, '20-30 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Rameur', 'full_body', 1, 2, 'cardio', '["dos"]'::jsonb, '15-20 min');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Circuit HIIT poids de corps', 'full_body', 2, 0, 'cardio', '["genoux","poignets"]'::jsonb, '6x40s/20s repos');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Squat jump', 'full_body', 2, 0, 'cardio', '["genoux","chevilles"]'::jsonb, '4x12');
insert into exercices (nom, zone, niveau, materiel, type, contre_indications, format) values ('Circuit léger poids de corps', 'full_body', 0, 0, 'renfo', '[]'::jsonb, '3 tours');

-- Import des recettes de départ (avec étapes de préparation générées)
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Porridge flocons d''avoine, banane, amandes', 'petit_dej', '["tonus","energie","reprise","endurance"]'::jsonb, true, false, false, false, '["gluten","lactose","noix"]'::jsonb, 14, '[{"nom":"flocons d''avoine","quantite":60,"unite":"g"},{"nom":"lait","quantite":200,"unite":"ml"},{"nom":"banane","quantite":1,"unite":"pièce"},{"nom":"amandes","quantite":15,"unite":"g"}]'::jsonb, '["Préparer tous les ingrédients : flocons d''avoine, lait, banane, amandes.","Assembler ou cuire selon la recette (poêle, mixeur ou simple assemblage selon les ingrédients).","Astuce batch cooking : préparer plusieurs portions à l''avance et garder au frais 2-3 jours."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Skyr, fruits rouges, granola', 'petit_dej', '["perte_poids","tonus"]'::jsonb, true, false, false, false, '["lactose","gluten"]'::jsonb, 20, '[{"nom":"skyr nature","quantite":200,"unite":"g"},{"nom":"fruits rouges","quantite":100,"unite":"g"},{"nom":"granola","quantite":30,"unite":"g"}]'::jsonb, '["Préparer tous les ingrédients : skyr nature, fruits rouges, granola.","Assembler ou cuire selon la recette (poêle, mixeur ou simple assemblage selon les ingrédients).","Astuce batch cooking : préparer plusieurs portions à l''avance et garder au frais 2-3 jours."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Œufs brouillés, avocat, pain complet', 'petit_dej', '["tonus","prise_masse"]'::jsonb, true, false, false, true, '["oeuf","gluten"]'::jsonb, 22, '[{"nom":"œufs","quantite":3,"unite":"pièce"},{"nom":"avocat","quantite":0.5,"unite":"pièce"},{"nom":"pain complet","quantite":2,"unite":"tranches"}]'::jsonb, '["Préparer tous les ingrédients : œufs, avocat, pain complet.","Assembler ou cuire selon la recette (poêle, mixeur ou simple assemblage selon les ingrédients).","Astuce batch cooking : préparer plusieurs portions à l''avance et garder au frais 2-3 jours."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Smoothie protéiné banane-épinards', 'petit_dej', '["perte_poids","tonus","energie"]'::jsonb, true, false, true, false, '["lactose"]'::jsonb, 25, '[{"nom":"lait","quantite":250,"unite":"ml"},{"nom":"whey protéine","quantite":30,"unite":"g"},{"nom":"banane","quantite":1,"unite":"pièce"},{"nom":"épinards frais","quantite":30,"unite":"g"}]'::jsonb, '["Préparer tous les ingrédients : lait, whey protéine, banane, épinards frais.","Assembler ou cuire selon la recette (poêle, mixeur ou simple assemblage selon les ingrédients).","Astuce batch cooking : préparer plusieurs portions à l''avance et garder au frais 2-3 jours."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Pancakes à la banane et à l''œuf', 'petit_dej', '["prise_masse","tonus"]'::jsonb, true, false, false, true, '["oeuf","gluten"]'::jsonb, 18, '[{"nom":"œufs","quantite":2,"unite":"pièce"},{"nom":"banane","quantite":1,"unite":"pièce"},{"nom":"farine complète","quantite":40,"unite":"g"}]'::jsonb, '["Préparer tous les ingrédients : œufs, banane, farine complète.","Assembler ou cuire selon la recette (poêle, mixeur ou simple assemblage selon les ingrédients).","Astuce batch cooking : préparer plusieurs portions à l''avance et garder au frais 2-3 jours."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Bowl petit-déj quinoa, lait végétal, fruits secs', 'petit_dej', '["energie","endurance"]'::jsonb, true, true, true, true, '["noix"]'::jsonb, 12, '[{"nom":"quinoa cuit","quantite":80,"unite":"g"},{"nom":"lait d''amande","quantite":150,"unite":"ml"},{"nom":"fruits secs","quantite":20,"unite":"g"}]'::jsonb, '["Préparer tous les ingrédients : quinoa cuit, lait d''amande, fruits secs.","Assembler ou cuire selon la recette (poêle, mixeur ou simple assemblage selon les ingrédients).","Astuce batch cooking : préparer plusieurs portions à l''avance et garder au frais 2-3 jours."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Tartines fromage blanc, miel, noix', 'petit_dej', '["tonus","reprise"]'::jsonb, true, false, false, false, '["lactose","gluten","noix"]'::jsonb, 16, '[{"nom":"pain complet","quantite":2,"unite":"tranches"},{"nom":"fromage blanc","quantite":100,"unite":"g"},{"nom":"miel","quantite":10,"unite":"g"}]'::jsonb, '["Préparer tous les ingrédients : pain complet, fromage blanc, miel.","Assembler ou cuire selon la recette (poêle, mixeur ou simple assemblage selon les ingrédients).","Astuce batch cooking : préparer plusieurs portions à l''avance et garder au frais 2-3 jours."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Omelette légumes et fromage', 'petit_dej', '["perte_poids","tonus"]'::jsonb, true, false, true, false, '["oeuf","lactose"]'::jsonb, 24, '[{"nom":"œufs","quantite":3,"unite":"pièce"},{"nom":"poivron","quantite":50,"unite":"g"},{"nom":"fromage râpé","quantite":20,"unite":"g"}]'::jsonb, '["Préparer tous les ingrédients : œufs, poivron, fromage râpé.","Assembler ou cuire selon la recette (poêle, mixeur ou simple assemblage selon les ingrédients).","Astuce batch cooking : préparer plusieurs portions à l''avance et garder au frais 2-3 jours."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Porridge protéiné cacao', 'petit_dej', '["prise_masse","tonus"]'::jsonb, true, false, false, false, '["gluten","lactose"]'::jsonb, 28, '[{"nom":"flocons d''avoine","quantite":70,"unite":"g"},{"nom":"lait","quantite":250,"unite":"ml"},{"nom":"whey chocolat","quantite":30,"unite":"g"}]'::jsonb, '["Préparer tous les ingrédients : flocons d''avoine, lait, whey chocolat.","Assembler ou cuire selon la recette (poêle, mixeur ou simple assemblage selon les ingrédients).","Astuce batch cooking : préparer plusieurs portions à l''avance et garder au frais 2-3 jours."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Fruits frais et poignée d''oléagineux', 'petit_dej', '["perte_poids","energie"]'::jsonb, true, true, true, true, '["noix"]'::jsonb, 8, '[{"nom":"fruits de saison","quantite":200,"unite":"g"},{"nom":"amandes/noix","quantite":25,"unite":"g"}]'::jsonb, '["Préparer tous les ingrédients : fruits de saison, amandes/noix.","Assembler ou cuire selon la recette (poêle, mixeur ou simple assemblage selon les ingrédients).","Astuce batch cooking : préparer plusieurs portions à l''avance et garder au frais 2-3 jours."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Yaourt grec, muesli, graines de chia', 'petit_dej', '["tonus","endurance"]'::jsonb, true, false, false, false, '["lactose","gluten"]'::jsonb, 19, '[{"nom":"yaourt grec","quantite":200,"unite":"g"},{"nom":"muesli","quantite":30,"unite":"g"},{"nom":"graines de chia","quantite":10,"unite":"g"}]'::jsonb, '["Préparer tous les ingrédients : yaourt grec, muesli, graines de chia.","Assembler ou cuire selon la recette (poêle, mixeur ou simple assemblage selon les ingrédients).","Astuce batch cooking : préparer plusieurs portions à l''avance et garder au frais 2-3 jours."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Wrap œuf, jambon blanc, épinards', 'petit_dej', '["tonus","prise_masse"]'::jsonb, false, false, false, true, '["oeuf","gluten","porc"]'::jsonb, 26, '[{"nom":"tortilla complète","quantite":1,"unite":"pièce"},{"nom":"œufs","quantite":2,"unite":"pièce"},{"nom":"jambon blanc","quantite":50,"unite":"g"}]'::jsonb, '["Préparer tous les ingrédients : tortilla complète, œufs, jambon blanc.","Assembler ou cuire selon la recette (poêle, mixeur ou simple assemblage selon les ingrédients).","Astuce batch cooking : préparer plusieurs portions à l''avance et garder au frais 2-3 jours."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Poulet grillé, riz complet, brocolis', 'dejeuner_diner', '["tonus","prise_masse","perte_poids"]'::jsonb, false, false, true, true, '[]'::jsonb, 38, '[{"nom":"blanc de poulet","quantite":150,"unite":"g"},{"nom":"riz complet","quantite":80,"unite":"g"},{"nom":"brocolis","quantite":150,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : brocolis.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : blanc de poulet.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : riz complet.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Pavé de saumon, patate douce, haricots verts', 'dejeuner_diner', '["tonus","energie","endurance"]'::jsonb, false, false, true, true, '["poisson"]'::jsonb, 32, '[{"nom":"pavé de saumon","quantite":150,"unite":"g"},{"nom":"patate douce","quantite":200,"unite":"g"},{"nom":"haricots verts","quantite":150,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : haricots verts.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : pavé de saumon.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : patate douce.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Bœuf haché maigre, quinoa, haricots rouges', 'dejeuner_diner', '["prise_masse","tonus"]'::jsonb, false, false, true, true, '[]'::jsonb, 35, '[{"nom":"bœuf haché 5%","quantite":150,"unite":"g"},{"nom":"quinoa","quantite":80,"unite":"g"},{"nom":"haricots rouges","quantite":100,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : bœuf haché 5%, haricots rouges.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : quinoa.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Salade poulet, quinoa, avocat, tomates', 'dejeuner_diner', '["perte_poids","tonus"]'::jsonb, false, false, true, true, '[]'::jsonb, 30, '[{"nom":"blanc de poulet","quantite":120,"unite":"g"},{"nom":"quinoa","quantite":60,"unite":"g"},{"nom":"avocat","quantite":0.5,"unite":"pièce"},{"nom":"tomates cerises","quantite":100,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : avocat, tomates cerises.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : blanc de poulet.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : quinoa.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Tofu mariné, légumes sautés, riz', 'dejeuner_diner', '["perte_poids","tonus","energie"]'::jsonb, true, true, true, true, '["soja"]'::jsonb, 22, '[{"nom":"tofu ferme","quantite":150,"unite":"g"},{"nom":"légumes variés","quantite":200,"unite":"g"},{"nom":"riz","quantite":80,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : légumes variés.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : tofu ferme.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : riz.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Escalope de dinde, pâtes complètes, courgettes', 'dejeuner_diner', '["prise_masse","tonus"]'::jsonb, false, false, false, true, '["gluten"]'::jsonb, 34, '[{"nom":"escalope de dinde","quantite":150,"unite":"g"},{"nom":"pâtes complètes","quantite":80,"unite":"g"},{"nom":"courgettes","quantite":150,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : courgettes.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : escalope de dinde.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : pâtes complètes.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Cabillaud vapeur, légumes, riz basmati', 'dejeuner_diner', '["perte_poids","energie"]'::jsonb, false, false, true, true, '["poisson"]'::jsonb, 28, '[{"nom":"filet de cabillaud","quantite":150,"unite":"g"},{"nom":"légumes vapeur","quantite":200,"unite":"g"},{"nom":"riz basmati","quantite":70,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : légumes vapeur.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : filet de cabillaud.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : riz basmati.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Chili sin carne (haricots rouges, maïs)', 'dejeuner_diner', '["perte_poids","tonus","endurance"]'::jsonb, true, true, true, true, '[]'::jsonb, 18, '[{"nom":"haricots rouges","quantite":200,"unite":"g"},{"nom":"maïs","quantite":80,"unite":"g"},{"nom":"tomates concassées","quantite":200,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : maïs, tomates concassées.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : haricots rouges.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Lentilles corail, légumes racines', 'dejeuner_diner', '["perte_poids","energie","endurance"]'::jsonb, true, true, true, true, '[]'::jsonb, 20, '[{"nom":"lentilles corail","quantite":150,"unite":"g"},{"nom":"carottes","quantite":100,"unite":"g"},{"nom":"oignons","quantite":50,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : carottes, oignons.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : lentilles corail.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Steak haché, pommes de terre, salade verte', 'dejeuner_diner', '["prise_masse","tonus"]'::jsonb, false, false, true, true, '[]'::jsonb, 33, '[{"nom":"steak haché 5%","quantite":150,"unite":"g"},{"nom":"pommes de terre","quantite":200,"unite":"g"},{"nom":"salade verte","quantite":80,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : salade verte.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : steak haché 5%.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : pommes de terre.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Poke bowl saumon, riz vinaigré, edamame', 'dejeuner_diner', '["tonus","energie"]'::jsonb, false, false, true, true, '["poisson","soja"]'::jsonb, 29, '[{"nom":"saumon cru mariné","quantite":120,"unite":"g"},{"nom":"riz vinaigré","quantite":100,"unite":"g"},{"nom":"edamame","quantite":60,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : saumon cru mariné, edamame.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : riz vinaigré.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Curry de pois chiches, lait de coco, riz', 'dejeuner_diner', '["prise_masse","energie"]'::jsonb, true, true, true, true, '[]'::jsonb, 16, '[{"nom":"pois chiches","quantite":200,"unite":"g"},{"nom":"lait de coco","quantite":100,"unite":"ml"},{"nom":"riz","quantite":80,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : lait de coco.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : pois chiches.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : riz.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Grande omelette, salade composée', 'dejeuner_diner', '["perte_poids","tonus"]'::jsonb, true, false, true, false, '["oeuf","lactose"]'::jsonb, 26, '[{"nom":"œufs","quantite":4,"unite":"pièce"},{"nom":"salade composée","quantite":150,"unite":"g"},{"nom":"fromage râpé","quantite":20,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : salade composée.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : œufs, fromage râpé.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Filet mignon de porc, riz, légumes sautés', 'dejeuner_diner', '["prise_masse","tonus"]'::jsonb, false, false, true, true, '["porc"]'::jsonb, 31, '[{"nom":"filet mignon de porc","quantite":150,"unite":"g"},{"nom":"riz","quantite":80,"unite":"g"},{"nom":"légumes sautés","quantite":150,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : légumes sautés.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : filet mignon de porc.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : riz.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Crevettes sautées, nouilles de riz, légumes', 'dejeuner_diner', '["perte_poids","tonus"]'::jsonb, false, false, true, true, '["fruits_de_mer"]'::jsonb, 27, '[{"nom":"crevettes","quantite":150,"unite":"g"},{"nom":"nouilles de riz","quantite":80,"unite":"g"},{"nom":"légumes variés","quantite":150,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : légumes variés.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : crevettes.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : nouilles de riz.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Pâtes complètes, thon, tomates cerises', 'dejeuner_diner', '["tonus","energie","endurance"]'::jsonb, false, false, false, true, '["poisson","gluten"]'::jsonb, 30, '[{"nom":"pâtes complètes","quantite":90,"unite":"g"},{"nom":"thon au naturel","quantite":120,"unite":"g"},{"nom":"tomates cerises","quantite":100,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : tomates cerises.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : thon au naturel.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : pâtes complètes.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Buddha bowl pois chiches, quinoa, légumes rôtis', 'dejeuner_diner', '["perte_poids","energie","endurance"]'::jsonb, true, true, true, true, '[]'::jsonb, 17, '[{"nom":"pois chiches","quantite":150,"unite":"g"},{"nom":"quinoa","quantite":70,"unite":"g"},{"nom":"légumes rôtis","quantite":150,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : légumes rôtis.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : pois chiches.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : quinoa.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Poulet au curry léger, légumes, riz', 'dejeuner_diner', '["tonus","prise_masse"]'::jsonb, false, false, true, false, '["lactose"]'::jsonb, 33, '[{"nom":"blanc de poulet","quantite":150,"unite":"g"},{"nom":"lait de coco","quantite":80,"unite":"ml"},{"nom":"riz","quantite":80,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : lait de coco.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : blanc de poulet.","Cuire le féculent en grande quantité (casserole ou autocuiseur) : riz.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Quiche légumes maison, salade', 'dejeuner_diner', '["tonus"]'::jsonb, true, false, false, false, '["oeuf","gluten","lactose"]'::jsonb, 16, '[{"nom":"pâte brisée","quantite":1,"unite":"portion"},{"nom":"œufs","quantite":3,"unite":"pièce"},{"nom":"légumes variés","quantite":150,"unite":"g"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : pâte brisée, légumes variés.","Cuire la source de protéine en grande quantité (poêle, plancha ou four) : œufs.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Soupe complète légumineuses et légumes', 'dejeuner_diner', '["perte_poids","energie"]'::jsonb, true, true, true, true, '[]'::jsonb, 14, '[{"nom":"légumineuses","quantite":150,"unite":"g"},{"nom":"légumes variés","quantite":200,"unite":"g"},{"nom":"bouillon","quantite":300,"unite":"ml"}]'::jsonb, '["Laver et couper tous les légumes en une seule fois pour toute la semaine : légumineuses, légumes variés, bouillon.","Assaisonner l''ensemble, puis répartir en portions individuelles dans des contenants hermétiques.","Réfrigérer jusqu''à 4 jours, ou congeler les portions en trop pour plus tard."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Fruit frais et amandes', 'collation', '["perte_poids","energie"]'::jsonb, true, true, true, true, '["noix"]'::jsonb, 5, '[{"nom":"fruit de saison","quantite":1,"unite":"pièce"},{"nom":"amandes","quantite":15,"unite":"g"}]'::jsonb, '["Préparer les portions : fruit de saison, amandes.","Répartir dans des contenants individuels pour la semaine, garder au frais."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Skyr nature et miel', 'collation', '["perte_poids","tonus"]'::jsonb, true, false, true, false, '["lactose"]'::jsonb, 16, '[{"nom":"skyr nature","quantite":150,"unite":"g"},{"nom":"miel","quantite":5,"unite":"g"}]'::jsonb, '["Préparer les portions : skyr nature, miel.","Répartir dans des contenants individuels pour la semaine, garder au frais."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Shaker whey protéine + eau/lait', 'collation', '["prise_masse","tonus"]'::jsonb, true, false, true, false, '["lactose"]'::jsonb, 24, '[{"nom":"whey protéine","quantite":30,"unite":"g"},{"nom":"lait ou eau","quantite":250,"unite":"ml"}]'::jsonb, '["Préparer les portions : whey protéine, lait ou eau.","Répartir dans des contenants individuels pour la semaine, garder au frais."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Barre de céréales maison flocons d''avoine', 'collation', '["energie","endurance"]'::jsonb, true, true, false, true, '["gluten"]'::jsonb, 6, '[{"nom":"flocons d''avoine","quantite":40,"unite":"g"},{"nom":"miel","quantite":15,"unite":"g"},{"nom":"fruits secs","quantite":20,"unite":"g"}]'::jsonb, '["Préparer les portions : flocons d''avoine, miel, fruits secs.","Répartir dans des contenants individuels pour la semaine, garder au frais."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Œufs durs', 'collation', '["perte_poids","tonus"]'::jsonb, true, false, true, true, '["oeuf"]'::jsonb, 12, '[{"nom":"œufs","quantite":2,"unite":"pièce"}]'::jsonb, '["Préparer les portions : œufs.","Répartir dans des contenants individuels pour la semaine, garder au frais."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Bâtonnets de légumes et houmous', 'collation', '["perte_poids","energie"]'::jsonb, true, true, true, true, '[]'::jsonb, 7, '[{"nom":"carottes/concombre","quantite":150,"unite":"g"},{"nom":"houmous","quantite":50,"unite":"g"}]'::jsonb, '["Préparer les portions : carottes/concombre, houmous.","Répartir dans des contenants individuels pour la semaine, garder au frais."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Fromage blanc et fruits rouges', 'collation', '["perte_poids","tonus"]'::jsonb, true, false, true, false, '["lactose"]'::jsonb, 14, '[{"nom":"fromage blanc","quantite":150,"unite":"g"},{"nom":"fruits rouges","quantite":80,"unite":"g"}]'::jsonb, '["Préparer les portions : fromage blanc, fruits rouges.","Répartir dans des contenants individuels pour la semaine, garder au frais."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Tartine beurre de cacahuète et banane', 'collation', '["prise_masse","energie"]'::jsonb, true, true, false, true, '["gluten","arachides"]'::jsonb, 9, '[{"nom":"pain complet","quantite":1,"unite":"tranche"},{"nom":"beurre de cacahuète","quantite":20,"unite":"g"},{"nom":"banane","quantite":0.5,"unite":"pièce"}]'::jsonb, '["Préparer les portions : pain complet, beurre de cacahuète, banane.","Répartir dans des contenants individuels pour la semaine, garder au frais."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Mélange noix et fruits secs', 'collation', '["prise_masse","endurance"]'::jsonb, true, true, true, true, '["noix"]'::jsonb, 8, '[{"nom":"noix mélangées","quantite":30,"unite":"g"},{"nom":"fruits secs","quantite":20,"unite":"g"}]'::jsonb, '["Préparer les portions : noix mélangées, fruits secs.","Répartir dans des contenants individuels pour la semaine, garder au frais."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Yaourt grec et graines de chia', 'collation', '["tonus","perte_poids"]'::jsonb, true, false, true, false, '["lactose"]'::jsonb, 15, '[{"nom":"yaourt grec","quantite":150,"unite":"g"},{"nom":"graines de chia","quantite":10,"unite":"g"}]'::jsonb, '["Préparer les portions : yaourt grec, graines de chia.","Répartir dans des contenants individuels pour la semaine, garder au frais."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Pomme et fromage type comté', 'collation', '["tonus","energie"]'::jsonb, true, false, true, false, '["lactose"]'::jsonb, 10, '[{"nom":"pomme","quantite":1,"unite":"pièce"},{"nom":"fromage","quantite":30,"unite":"g"}]'::jsonb, '["Préparer les portions : pomme, fromage.","Répartir dans des contenants individuels pour la semaine, garder au frais."]'::jsonb);
insert into recettes (nom, repas, profils, vegetarien, vegan, sans_gluten, sans_lactose, contient, proteines_g, ingredients, etapes) values ('Smoothie vegan mangue-lait de coco', 'collation', '["energie","perte_poids"]'::jsonb, true, true, true, true, '[]'::jsonb, 4, '[{"nom":"mangue","quantite":100,"unite":"g"},{"nom":"lait de coco","quantite":150,"unite":"ml"}]'::jsonb, '["Préparer les portions : mangue, lait de coco.","Répartir dans des contenants individuels pour la semaine, garder au frais."]'::jsonb);
