-- Marque les exercices polyarticulaires (mouvements composés, multi-articulations) pour
-- que le générateur les priorise sur les exercices d'isolation, comme demandé.
alter table exercices add column if not exists polyarticulaire boolean;

update exercices set polyarticulaire = true where nom in (
  'Marche du Fermier à la Barre Hexagonale',
  'Marche du Fermier avec Haltères',
  'Marche du Fermier avec Kettlebells',
  'Pull-Over à la Barre',
  'Rowing à la Machine, Assis',
  'Rowing à la Machine, Assis, Prise Large',
  'Rowing à la Poulie Basse, Assis',
  'Tirage Poitrine à la Machine',
  'Tirage Poitrine à la Poulie Haute',
  'Traction à la Barre Fixe, Prise Inversée',
  'Traction à la Barre Fixe, Prise Serrée',
  'Développé avec Haltères, Assis',
  'Développé avec Haltères, Debout',
  'Tirage au Visage à la Poulie Basse, Assis',
  'Tirage au Visage à la Poulie Haute',
  'Fente 2',
  'Fente à la Barre',
  'Fente avec Haltères',
  'Fente avec Kettlebells',
  'Fente Banc',
  'Fente Latérale',
  'Hip Thrust',
  'Pont',
  'Pont à la Barre',
  'Pont à la Barre sur Banc',
  'Pont avec Haltère',
  'Pont sur Banc',
  'Soulevé de Terre Sumo à la Barre',
  'Split Squat Bulgare',
  'Split Squat Bulgare à la Barre',
  'Split Squat Bulgare à la Ceinture à la Machine',
  'Split Squat Bulgare avec Haltères',
  'Squat à la Barre sur Banc',
  'Squat à la Ceinture à la Machine',
  'Squat à la Smith Machine',
  'Squat avec Haltères',
  'Squat avec Haltères sur Banc',
  'Squat avec Un Haltère',
  'Squat Devant à la Barre',
  'Squat Gobelet avec Haltère',
  'Squat Gobelet avec Kettlebell',
  'Squat Pendule à la Machine',
  'Step-up',
  'Good Morning à la Barre',
  'Soulevé de Terre à la Barre, Jambes Tendues',
  'Soulevé de Terre avec Haltères, Jambes Tendues',
  'Soulevé de Terre Roumain à la Barre',
  'Soulevé de Terre Roumain avec Kettlebells',
  'Développé Couché à la Barre',
  'Développé Couché à la Machine',
  'Développé Couché avec Haltères',
  'Développé Incliné à la Barre',
  'Développé Incliné à la Machine',
  'Dips à la Machine',
  'Pompes',
  'Pull-Over avec Haltère',
  'Hack Squat à la Landmine',
  'Hack Squat à la Machine',
  'Presse des Jambes',
  'Presse des Jambes à Une Jambe',
  'Presse des Jambes à Une Jambe, Assis',
  'Presse des Jambes, Assis',
  'Sissy Squat',
  'Sissy Squat avec Disque',
  'Squat à la Barre, Jambes Écartées',
  'Squat Pistol',
  'Squat Pistol avec Kettlebell',
  'Squat Sumo à la Ceinture à la Machine',
  'Rowing à la Barre, Buste Penché',
  'Soulevé de Terre à la Barre',
  'Traction à la Barre Fixe',
  'Dips sur Ballon',
  'Dips sur Banc',
  'Rowing Inversé sous Table',
  'Rowing Isométrique en W, Allongé',
  'Pompes Piquées (Pike Push-Up)'
);

update exercices set polyarticulaire = false where nom in (
  'Alpiniste',
  'Battement de Jambes',
  'Crunch',
  'Crunch à la Machine',
  'Crunch à la Poulie Haute, à Genoux',
  'Crunch à la Poulie Haute, Assis',
  'Crunch sur Ballon',
  'Gainage',
  'Insecte Mort',
  'Insecte Mort avec Ballon',
  'Planche',
  'Relevé de Jambes',
  'Relevé de Jambes à la Machine',
  'Relevé de Jambes Incliné',
  'Relevé de Jambes Suspendu',
  'Relevé du Buste',
  'Relevé du Buste Incliné',
  'Roulette à la Barre',
  'Roulette à la Barre EZ',
  'Roulette avec Haltères',
  'Roulette avec Roue Abdominale',
  'Adducteurs à la Machine',
  'Adducteurs à la Poulie Basse',
  'Hip Abduction',
  'Curl à la Barre, Prise Inversée',
  'Curl Araignée avec Haltères, Prise Inversée',
  'Curl Pupitre à la Barre EZ, Prise Inversée',
  'Curl Pupitre à la Barre, Prise Inversée',
  'Curl Pupitre à la Poulie Basse, Prise Inversée',
  'Curl Pupitre avec Haltères, Prise Inversée',
  'Curl Zottman, Assis',
  'Extension des Poignets à la Barre',
  'Extension des Poignets à la Poulie',
  'Extension des Poignets avec Haltères',
  'Flexion des Poignets à la Barre',
  'Flexion des Poignets à la Poulie',
  'Flexion des Poignets avec Haltères',
  'Flexion des Poignets avec Kettlebells',
  'Curl à la Barre',
  'Curl à la Barre EZ, Prise Large',
  'Curl à la Barre EZ, Prise Large 2',
  'Curl à la Barre, Prise Large',
  'Curl à la Machine',
  'Curl à la Poulie Basse',
  'Curl à la Poulie Basse, Prise Marteau',
  'Curl à la Poulie Haute',
  'Curl à Un Bras à la Poulie Basse',
  'Curl à Un Bras à la Poulie Haute',
  'Curl Alterné à la Machine',
  'Curl Alterné avec Haltères',
  'Curl Alterné avec Haltères, Prise Marteau',
  'Curl Araignée à la Barre',
  'Curl Araignée à la Barre EZ',
  'Curl Araignée avec Haltères',
  'Curl Araignée avec Haltères, Prise Marteau',
  'Curl avec Haltères',
  'Curl avec Haltères, Prise Marteau',
  'Curl avec Rotation avec Haltères',
  'Curl Concentré',
  'Curl Concentré à la Poulie Basse',
  'Curl Concentré avec Kettlebell',
  'Curl Incliné Alterné avec Rotation avec Haltères',
  'Curl Incliné avec Haltères',
  'Curl Incliné avec Rotation avec Haltères',
  'Curl Pupitre à Un Bras à la Machine',
  'Curl Pupitre à Un Bras avec Haltère, Debout',
  'Curl Pupitre Alterné avec Haltères',
  'Curl Pupitre Alterné avec Haltères, Prise Marteau',
  'Curl Pupitre avec Haltères',
  'Curl Pupitre avec Haltères, Prise Marteau',
  'Curl Pupitre Zottman',
  'Curl Pupitre Zottman à Un Bras, Debout',
  'Curl Zottman',
  'Élévation Latérale à Un Bras à la Poulie Basse',
  'Face Pull',
  'Abduction',
  'Abduction de la Hanche à la Machine, Assis',
  'Abduction de la Hanche à la Machine, Debout',
  'Abduction de la Hanche à la Poulie Basse',
  'Abduction de la Hanche, Couché',
  'Battement de Jambes Ventral sur Banc',
  'Extension de la Hanche',
  'Extension de la Hanche à la Machine 2',
  'Extension de la Hanche à la Poulie Basse',
  'Extension de la Hanche sur Banc',
  'Extension de la Hanche, Genou Plié',
  'Kick Back',
  'Presse Allongé',
  'Rdl',
  'Relevé de Bassin',
  'Relevé de Bassin à la Barre',
  'Relevé de Bassin à la Smith Machine',
  'Relevé de Bassin avec Haltères',
  'Relevé de Bassin sur Ballon',
  'Swing à Un Bras avec Kettlebell',
  'Swing avec Haltère',
  'Swing avec Kettlebell',
  'Flexion des Jambes, Assis',
  'Flexion des Jambes, Couché',
  'Flexion des Jambes, Debout',
  'Leg Curl',
  'Extension du Buste',
  'Extension du Buste à la Machine',
  'Extension du Buste sur Ballon',
  'Superman',
  'Étirement en Fente au Mur, Debout',
  'Extension des Mollets à la Barre, Assis',
  'Extension des Mollets à la Barre, Debout',
  'Extension des Mollets à la Machine, Assis',
  'Extension des Mollets à la Presse',
  'Extension des Mollets à Une Jambe à la Smith Machine, Debout',
  'Extension des Mollets à Une Jambe avec Haltère, Debout',
  'Extension des Mollets à Une Jambe, Debout',
  'Extension des Mollets avec Haltères, Assis',
  'Crunch avec Rotation',
  'Flexion Latérale à la Poulie Basse',
  'Flexion Latérale avec Haltère',
  'Planche Latérale',
  'Presse Pallof à la Poulie',
  'Presse Pallof à la Poulie, à Genoux',
  'Presse Pallof à la Poulie, Couché',
  'Relevé du Buste avec Rotation',
  'Relevé du Buste Incliné avec Rotation',
  'Rotation du Buste à la Barre',
  'Rotation du Buste à la Landmine',
  'Rotation du Buste à la Machine',
  'Rotation du Buste à la Poulie',
  'Rotation du Buste à la Poulie, Assis',
  'Rotation Russe',
  'Rotation Russe avec Haltère',
  'Rotation Russe avec Kettlebell',
  'Écarté à la Poulie',
  'Écarté à la Poulie Basse',
  'Écarté à la Poulie Haute',
  'Écarté avec Haltères',
  'Pec Fly',
  'Back Extension',
  'Chaise',
  'Extension des Jambes',
  'Extension des Jambes à Une Jambe',
  'Extension des Jambes à Une Jambe à la Poulie',
  'Extension Fessier',
  'Élévation Latérale à la Landmine (Dos)',
  'Élévation Latérale à la Poulie Basse, Buste Penché (Dos)',
  'Oiseau Haltère',
  'Dip Assist',
  'Élévation Latérale',
  'Extension des Triceps à la Barre EZ, Assis',
  'Extension des Triceps à la Barre EZ, Couché',
  'Extension des Triceps à la Barre, Couché',
  'Extension des Triceps à la Machine',
  'Extension des Triceps à la Poulie Basse, Buste Penché',
  'Extension des Triceps à la Poulie Basse, Couché',
  'Extension des Triceps à la Poulie Basse, Couché, Prise Marteau',
  'Extension des Triceps à la Poulie Basse, Debout',
  'Extension des Triceps à la Poulie Basse, Debout, Prise Marteau',
  'Extension des Triceps à la Poulie Haute',
  'Extension des Triceps à la Poulie Haute, Assis',
  'Extension des Triceps à la Poulie Haute, Debout',
  'Extension des Triceps à la Poulie Haute, Prise Inversée',
  'Extension des Triceps à la Poulie Haute, Prise Marteau',
  'Extension des Triceps à Un Bras à la Poulie Basse sur Banc',
  'Extension des Triceps à Un Bras à la Poulie Basse, Buste Penché',
  'Extension des Triceps à Un Bras à la Poulie Haute, Debout',
  'Extension des Triceps à Un Bras à la Poulie Haute, Prise Inversée',
  'Extension des Triceps à Un Bras à la Poulie Haute, Prise Marteau',
  'Extension des Triceps à Un Bras avec Haltère, Assis',
  'Extension des Triceps à Un Bras avec Haltère, Buste Penché',
  'Extension des Triceps avec Haltères, Couché',
  'Extension des Triceps avec Un Haltère, Assis',
  'Extension des Triceps avec Un Haltère, Debout',
  'Extension des Triceps Incliné à la Barre EZ',
  'Extension des Triceps Incliné à la Poulie Basse',
  'Extension des Triceps Incliné à la Poulie Basse, Prise Marteau',
  'Extension Triceps Poulie',
  'Extension du Dos au Sol (Superman Dos)',
  'Élévation Frontale Isométrique, Sans Charge',
  'Gainage Épaules en Planche Haute',
  'Y-Raise au Sol, Bras Tendus',
  'Rotation d''Épaules en Cercles, Debout',
  'Haussement d''Épaules Isométrique, Maintien'
);
