-- Suppression des exercices écartés par la coach après relecture de la bibliothèque (126 exercices).
delete from exercices where nom in (
  'Pull Over Poulie',
  'Pull-Over à la Machine',
  'Pull-Over à la Poulie Haute, Assis',
  'Rowing à la Barre T, Buste Penché',
  'Rowing à la Barre T, Couché',
  'Rowing à la Landmine',
  'Rowing à la Barre, Couché',
  'Rowing à la Barre, Buste Penché, Prise Inversée',
  'Rowing à la Smith Machine, Buste Penché',
  'Rowing à la Poulie Basse, Assis, Prise Large',
  'Rowing à Un Bras à la Landmine, Buste Penché',
  'Rowing à Un Bras avec Kettlebell, Buste Penché',
  'Rowing avec Haltères, Buste Penché',
  'Rowing avec Haltères, Buste Penché, Prise Inversée',
  'Rowing Incliné à la Barre, Prise Inversée',
  'Rowing Incliné avec Haltères',
  'Rowing Poulie Basse',
  'Rowing Renégat avec Haltères',
  'Rowing Renégat avec Kettlebells',
  'Tirage Poitrine à la Machine, Prise Inversée',
  'Tirage Poitrine à la Poulie Haute, Bras Tendus',
  'Tirage Poitrine à la Poulie Haute, Prise Inversée',
  'Tirage Poitrine à la Poulie Haute, Prise Serrée',
  'Tirage Poitrine à Un Bras à la Poulie Haute',
  'Tirage Poitrine à Un Bras à la Poulie Haute, Bras Tendu',
  'Tirage Poitrine à Un Bras à la Poulie Haute, Bras Tendu 2',
  'Arraché à la Barre',
  'Arraché à Un Bras avec Haltère',
  'Arraché à Un Bras avec Kettlebell',
  'Développé à la Landmine, à Genoux',
  'Développé à la Landmine, Debout',
  'Développé à la Machine, Assis',
  'Développé à Un Bras à la Landmine, à Genoux',
  'Développé à Un Bras à la Landmine, Debout',
  'Développé à Un Bras avec Haltère, Debout',
  'Développé Arnold',
  'Développé Arnold à Un Bras',
  'Développé Arnold, Debout',
  'Développé Arnold, Debout 2',
  'Développé Devant à la Barre, Assis',
  'Développé Devant à la Barre, Debout',
  'Développé Devant à la Smith Machine, Assis',
  'Développé Devant à la Smith Machine, Debout',
  'Développé Nuque à la Barre, Assis',
  'Développé Nuque à la Smith Machine, Assis',
  'Développé Nuque à la Smith Machine, Debout',
  'Élévation Frontale à la Barre',
  'Élévation Frontale à la Barre, Assis',
  'Élévation Frontale à la Poulie Basse',
  'Élévation Frontale à Un Bras à la Poulie Basse',
  'Élévation Frontale à Un Bras à la Poulie Basse, Prise Marteau',
  'Élévation Frontale à Un Bras avec Haltère, Prise Marteau',
  'Élévation Frontale Alternée avec Haltères',
  'Élévation Frontale Alternée avec Haltères, Prise Marteau',
  'Élévation Frontale avec Haltères',
  'Élévation Latéral À La Poulie',
  'Élévation Frontale avec Un Haltère',
  'Élévation Latéral Poulie',
  'Élévation Latérale à la Landmine',
  'Élévation Latérale à la Machine',
  'Élévation Latérale Alternée avec Haltères, Buste Penché',
  'Élévation Latérale avec Haltère, Couché sur le Côté',
  'Élévation Latérale à la Poulie Basse',
  'Élévation Latérale à la Poulie Basse, Buste Penché',
  'Élévation Latérale avec Haltères',
  'Élévation Latérale avec Haltères, Assis',
  'Élévation Latérale avec Haltères, Buste Penché',
  'Élévation Latérale avec Kettlebells',
  'Oiseau à la Machine',
  'Oiseau à la Poulie Haute',
  'Rotation Externe à la Poulie, Debout',
  'Rotation Interne à la Poulie, Debout',
  'Seated Row',
  'Tirage Vertical à la Barre',
  'Tirage Vertical à la Barre EZ',
  'Tirage Vertical à la Poulie Basse',
  'Tirage Vertical à Un Bras avec Haltère',
  'Tirage Vertical avec Haltères',
  'Tirage Vertical avec Kettlebell',
  'Boxe',
  'Ergomètre de Ski',
  'Saut Double à la Corde',
  'Saut en Étoile',
  'Vélo Stationnaire',
  'Vélo Elliptique',
  'Ondulations Alternées avec Corde Ondulatoire',
  'Développé Couché à la Barre, Prise Large',
  'Développé Couché à la Barre, Prise Large 2',
  'Développé Couché à la Barre, Prise Serrée',
  'Développé Couché à la Barre, Prise Serrée 2',
  'Développé Couché à la Machine, Assis',
  'Développé Couché à la Poulie',
  'Développé Couché à la Poulie, Assis',
  'Développé Couché à la Smith Machine',
  'Développé Couché avec Haltères, Prise Serrée',
  'Développé Couché avec Haltères, Prise Serrée 2',
  'Développé Décliné à la Barre',
  'Développé Décliné à la Poulie',
  'Développé Décliné avec Haltères',
  'Développé Décliné à la Smith Machine',
  'Développé Incliné à la Poulie',
  'Développé Incliné à la Smith Machine',
  'Développé Incliné avec Haltères',
  'Développé Incliné avec Haltères, Prise Serrée',
  'Dips aux Barres Parallèles, Prise Serrée',
  'Dips aux Barres Parallèles',
  'Écarté à la Machine',
  'Écarté Décliné avec Haltères',
  'Écarté Incliné à la Poulie',
  'Écarté Incliné avec Haltères',
  'Pompes Déclinées',
  'Pompes Déclinées sur Ballon',
  'Pompes Inclinées',
  'Pompes Inclinées, Prise Serrée',
  'Pompes Inclinées sur Ballon',
  'Pompes, Prise Serrée',
  'Haussement d''Épaules à la Barre',
  'Haussement d''Épaules à la Barre Hexagonale',
  'Haussement d''Épaules à la Machine',
  'Haussement d''Épaules avec Haltères',
  'Rowing à Un Bras avec Haltère, Buste Penché',
  'Soulevé de Terre à la Barre Hexagonale',
  'Soulevé de Terre à la Smith Machine',
  'Soulevé de Terre avec Haltères',
  'Tirage Nuque à la Poulie Haute, Prise Large',
  'Tirage Poitrine à la Poulie Haute, Prise Large'
);
