-- Suppression des doublons repérés par la coach (2e vague, 185 exercices).
delete from exercices where nom in (
  'Crunch à la Machine',
  'Crunch à la Poulie Haute, à Genoux',
  'Crunch à la Poulie Haute, Assis',
  'Crunch sur Ballon',
  'Roulette à la Barre',
  'Roulette à la Barre EZ',
  'Roulette avec Haltères',
  'Roulette avec Roue Abdominale',
  'Insecte Mort',
  'Insecte Mort avec Ballon',
  'Relevé de Jambes',
  'Alpiniste',
  'Battement de Jambes',
  'Adducteurs à la Poulie Basse',
  'Hip Abduction',
  'Curl Pupitre à la Barre EZ, Prise Inversée',
  'Curl Pupitre à la Barre, Prise Inversée',
  'Curl Pupitre à la Poulie Basse, Prise Inversée',
  'Curl Pupitre avec Haltères, Prise Inversée',
  'Flexion des Poignets à la Barre',
  'Flexion des Poignets à la Poulie',
  'Flexion des Poignets avec Haltères',
  'Flexion des Poignets avec Kettlebells',
  'Extension des Poignets à la Barre',
  'Extension des Poignets à la Poulie',
  'Extension des Poignets avec Haltères',
  'Marche du Fermier à la Barre Hexagonale',
  'Marche du Fermier avec Haltères',
  'Marche du Fermier avec Kettlebells',
  'Curl à la Barre, Prise Inversée',
  'Curl Araignée avec Haltères, Prise Inversée',
  'Curl Zottman, Assis',
  'Étirement des Extenseurs du Poignet',
  'Étirement des Fléchisseurs du Poignet',
  'Curl à la Barre',
  'Curl à la Barre EZ, Prise Large',
  'Curl à la Barre EZ, Prise Large 2',
  'Curl à la Barre, Prise Large',
  'Curl à la Poulie Basse, Prise Marteau',
  'Curl à la Poulie Haute',
  'Curl à Un Bras à la Poulie Basse',
  'Curl à Un Bras à la Poulie Haute',
  'Curl avec Haltères, Prise Marteau',
  'Curl Araignée à la Barre',
  'Curl Araignée à la Barre EZ',
  'Curl Araignée avec Haltères',
  'Curl Araignée avec Haltères, Prise Marteau',
  'Curl Pupitre à Un Bras à la Machine',
  'Curl Pupitre à Un Bras avec Haltère, Debout',
  'Curl Pupitre avec Haltères',
  'Curl Pupitre avec Haltères, Prise Marteau',
  'Curl Alterné à la Machine',
  'Curl Alterné avec Haltères',
  'Curl Alterné avec Haltères, Prise Marteau',
  'Curl Concentré',
  'Curl Concentré à la Poulie Basse',
  'Curl Concentré avec Kettlebell',
  'Curl Pupitre Alterné avec Haltères',
  'Curl Pupitre Alterné avec Haltères, Prise Marteau',
  'Curl Pupitre Zottman',
  'Curl Pupitre Zottman à Un Bras, Debout',
  'Curl avec Rotation avec Haltères',
  'Curl Incliné avec Haltères',
  'Curl Incliné Alterné avec Rotation avec Haltères',
  'Curl Incliné avec Rotation avec Haltères',
  'Curl Zottman',
  'Rowing à la Poulie Basse, Assis',
  'Rowing à la Machine, Assis, Prise Large',
  'Tirage Poitrine à la Poulie Haute',
  'Étirement du Dos, Chat-Vache',
  'Étirement du Dos en Torsion, Assis',
  'Extension du Dos au Sol (Superman Dos)',
  'Développé avec Haltères, Assis',
  'Développé avec Haltères, Debout',
  'Élévation Latérale à Un Bras à la Poulie Basse',
  'Élévation Frontale Isométrique, Sans Charge',
  'Gainage Épaules en Planche Haute',
  'Extension de la Hanche',
  'Extension de la Hanche à la Poulie Basse',
  'Extension de la Hanche sur Banc',
  'Extension de la Hanche, Genou Plié',
  'Pont',
  'Pont à la Barre',
  'Pont à la Barre sur Banc',
  'Pont avec Haltère',
  'Pont sur Banc',
  'Relevé de Bassin',
  'Relevé de Bassin à la Barre',
  'Relevé de Bassin à la Smith Machine',
  'Relevé de Bassin avec Haltères',
  'Relevé de Bassin sur Ballon',
  'Squat avec Haltères sur Banc',
  'Squat avec Un Haltère',
  'Abduction de la Hanche à la Machine, Debout',
  'Abduction de la Hanche, Couché',
  'Fente 2',
  'Fente avec Kettlebells',
  'Split Squat Bulgare à la Barre',
  'Split Squat Bulgare avec Haltères',
  'Swing à Un Bras avec Kettlebell',
  'Swing avec Haltère',
  'Swing avec Kettlebell',
  'Squat Gobelet avec Kettlebell',
  'Battement de Jambes Ventral sur Banc',
  'Étirement du Piriforme, Allongé',
  'Escaliers Stationnaires',
  'Étirements Complets au Sol, Enchaînement Allongé',
  'Étirements Dynamiques Complets, Enchaînement Debout',
  'Flexion des Jambes, Couché',
  'Flexion des Jambes, Debout',
  'Extension du Buste',
  'Extension du Buste à la Machine',
  'Extension du Buste sur Ballon',
  'Soulevé de Terre Roumain avec Kettlebells',
  'Soulevé de Terre Roumain à la Barre',
  'Extension des Mollets à la Barre, Assis',
  'Extension des Mollets à la Barre, Debout',
  'Extension des Mollets à Une Jambe avec Haltère, Debout',
  'Extension des Mollets à Une Jambe, Debout',
  'Extension des Mollets avec Haltères, Assis',
  'Étirement du Mollet au Mur',
  'Étirement en Fente au Mur, Debout',
  'Rotation du Buste à la Barre',
  'Rotation du Buste à la Landmine',
  'Rotation du Buste à la Machine',
  'Rotation du Buste à la Poulie',
  'Rotation du Buste à la Poulie, Assis',
  'Presse Pallof à la Poulie',
  'Presse Pallof à la Poulie, à Genoux',
  'Presse Pallof à la Poulie, Couché',
  'Rotation Russe',
  'Rotation Russe avec Haltère',
  'Rotation Russe avec Kettlebell',
  'Flexion Latérale avec Haltère',
  'Crunch avec Rotation',
  'Écarté à la Poulie',
  'Écarté à la Poulie Basse',
  'Écarté à la Poulie Haute',
  'Écarté avec Haltères',
  'Développé Couché à la Machine',
  'Développé Incliné à la Barre',
  'Développé Incliné à la Machine',
  'Presse des Jambes à Une Jambe, Assis',
  'Presse des Jambes à Une Jambe',
  'Extension des Jambes à Une Jambe',
  'Extension des Jambes à Une Jambe à la Poulie',
  'Hack Squat à la Landmine',
  'Hack Squat à la Machine',
  'Sissy Squat',
  'Sissy Squat avec Disque',
  'Squat Pistol',
  'Squat Pistol avec Kettlebell',
  'Chaise',
  'Élévation Latérale à la Landmine (Dos)',
  'Haussement d''Épaules Isométrique, Maintien',
  'Oiseau Haltère',
  'Extension des Triceps à la Barre EZ, Assis',
  'Extension des Triceps à la Barre EZ, Couché',
  'Extension des Triceps à la Barre, Couché',
  'Extension des Triceps à la Machine',
  'Extension des Triceps à la Poulie Basse, Buste Penché',
  'Extension des Triceps à la Poulie Basse, Couché',
  'Extension des Triceps à la Poulie Basse, Couché, Prise Marteau',
  'Extension des Triceps à la Poulie Basse, Debout',
  'Extension des Triceps à la Poulie Basse, Debout, Prise Marteau',
  'Extension des Triceps à la Poulie Haute, Assis',
  'Extension des Triceps à la Poulie Haute, Debout',
  'Extension des Triceps à la Poulie Haute, Prise Inversée',
  'Extension des Triceps à la Poulie Haute, Prise Marteau',
  'Extension des Triceps à Un Bras à la Poulie Basse sur Banc',
  'Extension des Triceps à Un Bras à la Poulie Basse, Buste Penché',
  'Extension des Triceps à Un Bras à la Poulie Haute, Debout',
  'Extension des Triceps à Un Bras à la Poulie Haute, Prise Inversée',
  'Extension des Triceps à Un Bras à la Poulie Haute, Prise Marteau',
  'Extension des Triceps à Un Bras avec Haltère, Assis',
  'Extension des Triceps à Un Bras avec Haltère, Buste Penché',
  'Extension des Triceps avec Haltères, Couché',
  'Extension des Triceps avec Un Haltère, Assis',
  'Extension des Triceps avec Un Haltère, Debout',
  'Extension des Triceps Incliné à la Barre EZ',
  'Extension des Triceps Incliné à la Poulie Basse',
  'Extension des Triceps Incliné à la Poulie Basse, Prise Marteau',
  'Dips sur Ballon',
  'Dip Assist',
  'Élévation Latérale'
);
